version: '3.8'

services:
  incollab-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: incollab-backend-dev
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=3002
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=incollab
      - DATABASE_PASSWORD=incollab123
      - DATABASE_NAME=incollab_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
    networks:
      - incollab-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3002/api"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: incollab-nginx-dev
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - incollab-app
    networks:
      - incollab-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:15-alpine
    container_name: incollab-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: incollab_db
      POSTGRES_USER: incollab
      POSTGRES_PASSWORD: incollab123
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - incollab-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U incollab -d incollab_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: incollab-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    networks:
      - incollab-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data_dev:
    driver: local
  redis_data_dev:
    driver: local

networks:
  incollab-network:
    driver: bridge