import { IsDateString, IsOptional, IsNumber, Min } from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Type } from 'class-transformer';

/**
 * Date range filter for admin analytics
 */
export class DateRangeFilterDto {
  @ApiPropertyOptional({
    description: 'Start date for filtering (ISO format)',
    example: '2025-09-01T00:00:00Z',
  })
  @IsOptional()
  @IsDateString()
  startDate?: string;

  @ApiPropertyOptional({
    description: 'End date for filtering (ISO format)',
    example: '2025-10-31T23:59:59Z',
  })
  @IsOptional()
  @IsDateString()
  endDate?: string;
}

/**
 * Pagination query parameters
 */
export class PaginationDto {
  @ApiPropertyOptional({
    description: 'Page number (1-indexed)',
    example: 1,
    default: 1,
    type: Number,
  })
  @IsOptional()
  @Type(() => Number)
  @IsNumber()
  @Min(1)
  page?: number = 1;

  @ApiPropertyOptional({
    description: 'Number of items per page',
    example: 20,
    default: 20,
    type: Number,
  })
  @IsOptional()
  @Type(() => Number)
  @IsNumber()
  @Min(1)
  limit?: number = 20;
}

/**
 * Dashboard metrics response
 */
export class DashboardMetricsDto {
  @ApiProperty({ example: 3200, description: 'Total active brands on Hype Store' })
  totalActiveBrands: number;

  @ApiProperty({ example: 36, description: 'Percentage change vs last period' })
  totalActiveBrandsChange: number;

  @ApiProperty({ example: 3200, description: 'Total active stores on Hype Store' })
  totalActiveStores: number;

  @ApiProperty({ example: -2.9, description: 'Percentage change vs last period' })
  totalActiveStoresChange: number;

  @ApiProperty({ example: 17000, description: 'Total sales quantity (number of orders)' })
  totalSalesQuantity: number;

  @ApiProperty({ example: -2.9, description: 'Percentage change vs last period' })
  totalSalesQuantityChange: number;

  @ApiProperty({ example: 200000, description: 'Total sales amount in rupees' })
  totalSalesAmount: number;

  @ApiProperty({ example: -2.9, description: 'Percentage change vs last period' })
  totalSalesAmountChange: number;

  @ApiProperty({ example: 12000, description: 'Total cashback given (quantity)' })
  totalCashbackGivenQty: number;

  @ApiProperty({ example: -2.9, description: 'Percentage change vs last period' })
  totalCashbackGivenQtyChange: number;

  @ApiProperty({ example: 20000, description: 'Total cashback given (amount in rupees)' })
  totalCashbackGivenAmount: number;

  @ApiProperty({ example: -2.9, description: 'Percentage change vs last period' })
  totalCashbackGivenAmountChange: number;

  @ApiProperty({ example: 120000, description: 'Current amount in all wallets' })
  currentAmountInWallet: number;

  @ApiProperty({ example: -2.9, description: 'Percentage change vs last period' })
  currentAmountInWalletChange: number;

  @ApiProperty({ example: 200000, description: 'Lifetime amount credited to wallets' })
  lifetimeAmountInWallet: number;

  @ApiProperty({ example: -2.9, description: 'Percentage change vs last period' })
  lifetimeAmountInWalletChange: number;
}

/**
 * Brand with stores info
 */
export class BrandWithStoresDto {
  @ApiProperty({ example: 1, description: 'Brand ID' })
  id: number;

  @ApiProperty({ example: 'Myntra', description: 'Brand name' })
  brandName: string;

  @ApiProperty({ example: 'https://cdn.example.com/myntra-logo.png', description: 'Brand logo URL' })
  logoUrl: string;

  @ApiProperty({ example: 'Fashion | Accessories | Lifestyle', description: 'Brand categories' })
  category: string;

  @ApiProperty({ example: 1, description: 'Number of active stores' })
  activeStoreCount: number;

  @ApiProperty({ example: '2026-01-28T00:00:00Z', description: 'Brand creation date' })
  createdAt: string;

  @ApiProperty({ example: 50000, description: 'Total revenue generated' })
  totalRevenue: number;

  @ApiProperty({ example: 250, description: 'Total orders count' })
  totalOrders: number;
}

/**
 * Brand summary for store listing
 */
export class BrandSummaryDto {
  @ApiProperty({ example: 1, description: 'Brand ID' })
  id: number;

  @ApiProperty({ example: 'Myntra', description: 'Brand name' })
  name: string;
}

/**
 * Store details for a brand
 */
export class BrandStoreDto {
  @ApiProperty({ example: 10, description: 'Store ID' })
  id: number;

  @ApiProperty({ example: 'Myntra Store', description: 'Store name' })
  storeName: string;

  @ApiPropertyOptional({ example: 'myntra-store', description: 'Store slug' })
  storeSlug?: string | null;

  @ApiProperty({ example: true, description: 'Whether the store is active' })
  isActive: boolean;

  @ApiProperty({ example: true, description: 'Whether the store is verified' })
  isVerified: boolean;

  @ApiProperty({ example: 250, description: 'Total orders processed by this store' })
  totalOrders: number;

  @ApiProperty({ example: 50000, description: 'Total revenue generated by this store' })
  totalRevenue: number;

  @ApiProperty({ example: 2000, description: 'Total cashback given by this store' })
  totalCashbackGiven: number;

  @ApiProperty({ example: '2026-01-28T00:00:00Z', description: 'Store creation date' })
  createdAt: string;

  @ApiProperty({ example: '2026-02-10T00:00:00Z', description: 'Store update date' })
  updatedAt: string;
}

/**
 * Brand stores response
 */
export class BrandStoresResponseDto {
  @ApiProperty({ type: BrandSummaryDto })
  brand: BrandSummaryDto;

  @ApiProperty({ type: [BrandStoreDto] })
  stores: BrandStoreDto[];
}

/**
 * Brands list response with pagination
 */
export class BrandsListResponseDto {
  @ApiProperty({ type: [BrandWithStoresDto] })
  data: BrandWithStoresDto[];

  @ApiProperty({ example: 100, description: 'Total number of brands' })
  total: number;

  @ApiProperty({ example: 1, description: 'Current page' })
  page: number;

  @ApiProperty({ example: 20, description: 'Items per page' })
  limit: number;

  @ApiProperty({ example: 5, description: 'Total pages' })
  totalPages: number;
}

/**
 * Performance metrics for a store
 */
export class PerformanceMetricsDto {
  @ApiProperty({ example: 1.4, description: 'Expected ROI multiplier' })
  expectedRoi: number;

  @ApiProperty({ example: 13100, description: 'Estimated engagement count' })
  estimatedEngagement: number;

  @ApiProperty({ example: 210000, description: 'Estimated reach count' })
  estimatedReach: number;

  @ApiProperty({ example: 'Elite', description: 'Performance tier (Elite, Premium, Standard)' })
  performanceTier: string;
}

/**
 * Cashback configuration for a store
 */
export class CashbackConfigDto {
  @ApiProperty({ example: 200, description: 'Minimum cashback for Reel/Post' })
  reelPostMinCashback: number;

  @ApiProperty({ example: 4000, description: 'Maximum cashback for Reel/Post' })
  reelPostMaxCashback: number;

  @ApiProperty({ example: 200, description: 'Minimum cashback for Story' })
  storyMinCashback: number;

  @ApiProperty({ example: 4000, description: 'Maximum cashback for Story' })
  storyMaxCashback: number;

  @ApiProperty({ example: 3, description: 'Monthly cashback claim count per creator' })
  monthlyClaimCount: number;

  @ApiProperty({ example: 'OPTIMIZED_SPEND', description: 'Cashback claim strategy' })
  claimStrategy: string;
}

/**
 * Wallet metrics for a store
 */
export class WalletMetricsDto {
  @ApiProperty({ example: 110000, description: 'Current wallet amount' })
  currentWalletAmount: number;

  @ApiProperty({ example: 36, description: 'Percentage change vs last period' })
  currentWalletAmountChange: number;

  @ApiProperty({ example: 110000, description: 'Total cashback amount used' })
  totalCashbackUsed: number;

  @ApiProperty({ example: 36, description: 'Percentage change vs last period' })
  totalCashbackUsedChange: number;

  @ApiProperty({ example: 400, description: 'Total orders count' })
  totalOrders: number;

  @ApiProperty({ example: 36, description: 'Percentage change vs last period' })
  totalOrdersChange: number;

  @ApiProperty({ example: 4260000, description: 'Total sales amount' })
  totalSales: number;

  @ApiProperty({ example: 36, description: 'Percentage change vs last period' })
  totalSalesChange: number;
}

/**
 * Store detail response
 */
export class StoreDetailDto {
  @ApiProperty({ example: 1, description: 'Store ID' })
  id: number;

  @ApiProperty({ example: 'Myntra Store', description: 'Store name' })
  storeName: string;

  @ApiProperty({ example: 'myntra-store', description: 'Store slug' })
  storeSlug: string;

  @ApiProperty({ example: true, description: 'Whether the store is active' })
  isActive: boolean;

  @ApiProperty({ example: true, description: 'Whether the store is verified' })
  isVerified: boolean;

  @ApiProperty({ type: PerformanceMetricsDto })
  performance: PerformanceMetricsDto;

  @ApiProperty({ type: CashbackConfigDto })
  cashbackConfig: CashbackConfigDto;

  @ApiProperty({ type: WalletMetricsDto })
  walletMetrics: WalletMetricsDto;

  @ApiProperty({ example: '2026-01-28T00:00:00Z', description: 'Store creation date' })
  createdAt: string;

  @ApiProperty({ example: '2026-03-15T10:00:00Z', description: 'Store update date' })
  updatedAt: string;
}

/**
 * Order listing item
 */
export class OrderListItemDto {
  @ApiProperty({ example: 123, description: 'Order ID' })
  id: number;

  @ApiProperty({ example: 42, description: 'Influencer ID who used the coupon', nullable: true })
  influencerId: number | null;

  @ApiProperty({ example: 'Sneha Shah', description: 'Customer name' })
  customerName: string;

  @ApiProperty({ example: 'ORD-2026-12345', description: 'External order ID' })
  externalOrderId: string;

  @ApiProperty({ example: 'MYNTRA-000123-A3F2B1', description: 'Coupon code used' })
  couponCode: string;

  @ApiProperty({ example: 10000, description: 'Order value in rupees' })
  orderValue: number;

  @ApiProperty({ example: 1000, description: 'Cashback amount in rupees' })
  cashbackAmount: number;

  @ApiProperty({ example: '2025-10-02T00:00:00Z', description: 'Order date' })
  orderDate: string;

  @ApiProperty({ example: 'CREDITED', description: 'Cashback status' })
  cashbackStatus: string;

  @ApiProperty({ example: 'DELIVERED', description: 'Order status' })
  orderStatus: string;
}

/**
 * Orders list response with pagination
 */
export class OrdersListResponseDto {
  @ApiProperty({ type: [OrderListItemDto] })
  orders: OrderListItemDto[];

  @ApiProperty({ example: 180, description: 'Total number of orders' })
  total: number;

  @ApiProperty({ example: 1, description: 'Current page' })
  page: number;

  @ApiProperty({ example: 20, description: 'Items per page' })
  limit: number;

  @ApiProperty({ example: 9, description: 'Total pages' })
  totalPages: number;
}

/**
 * Wallet transaction item
 */
export class WalletTransactionItemDto {
  @ApiProperty({ example: 12, description: 'Transaction ID' })
  id: number;

  @ApiProperty({ example: 'ADD_MONEY', description: 'Transaction type' })
  transactionType: string;

  @ApiProperty({ example: 'Wallet recharge', description: 'Transaction description' })
  description: string;

  @ApiProperty({ example: 36000, description: 'Transaction amount' })
  amount: number;

  @ApiProperty({ example: 136000, description: 'Balance after transaction' })
  balanceAfter: number;

  @ApiProperty({ example: 'SUCCESS', description: 'Transaction status (SUCCESS/FAILED)' })
  status: string;

  @ApiProperty({ example: 'UPI', description: 'Payment method' })
  paymentMethod: string;

  @ApiProperty({ example: 'pay_123456789', description: 'Payment reference ID' })
  paymentReferenceId: string;

  @ApiProperty({ example: '2026-03-22T01:54:00Z', description: 'Transaction date' })
  createdAt: string;
}

/**
 * Wallet transactions list response with pagination
 */
export class WalletTransactionsListResponseDto {
  @ApiProperty({ type: [WalletTransactionItemDto] })
  transactions: WalletTransactionItemDto[];

  @ApiProperty({ example: 50, description: 'Total number of transactions' })
  total: number;

  @ApiProperty({ example: 1, description: 'Current page' })
  page: number;

  @ApiProperty({ example: 20, description: 'Items per page' })
  limit: number;

  @ApiProperty({ example: 3, description: 'Total pages' })
  totalPages: number;
}
