ALTER TABLE consumers
ADD COLUMN IF NOT EXISTS name VARCHAR(100) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS profile_image TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS date_of_birth DATE DEFAULT NULL,
ADD COLUMN IF NOT EXISTS phone_hash VARCHAR(64) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS fcm_token VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;

CREATE UNIQUE INDEX IF NOT EXISTS consumers_phone_hash_unique ON consumers(phone_hash);
